/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_stitchimage_ImageProc */

#ifndef _Included_com_example_stitchimage_ImageProc
#define _Included_com_example_stitchimage_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_stitchimage_ImageProc
 * Method:    FindFeatures
 * Signature: (J)V
 */
//JNIEXPORT void JNICALL Java_com_example_stitchimage_ImageProc_FindFeatures
//  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_stitchimage_ImageProc
 * Method:    encode
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_stitchimage_ImageProc_encode
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
